export const site = {
  brandName: "iCONiC collection",
  siteUrl: "https://www.iconic-collection.ro",
  headline: "Case proiectate și executate corect, personalizate pentru terenul tău, conform reglementărilor urbanistice",
  subheadline:
    "Tu vii cu terenul și obiectivul, iar noi ne putem ocupa de ce ai nevoie: concept, studiu geotehnic, proiect complet (arhitectură, structură și instalații), documentații pentru autorizare, urmărire de șantier, dirigenție și execuție.",
  heroBadges: [
    "Proiectare completă pentru casă",
    "Documentații și pași pentru autorizare",
    "Execuție și coordonare până la capăt",
  ],
  cta: {
    primary: { label: "Contactează-ne", href: "/contact" },
    secondary: { label: "Vezi modele", href: "/modele" },
  },

  pachete: {
    title: "Pașii Proiectului",
    items: [
      "Discuția inițială și analiza terenului",
      "Ridicare topografică",
      "Studiu geotehnic",
      "Conceptul casei și organizarea soluției",
      "Documentația pentru autorizare",
      "Proiectul tehnic și detaliile de execuție",
      "Coordonare și clarificări pe parcurs",
      "Execuție",
    ],
    actions: [{ label: "Vezi pașii proiectului", href: "/pachete" }],
  },

  models: [
    {
      slug: "iconic-1story-black",
      name: "CASA PARTER-iCONiC 1-story BLACK",
      summary: "Varianta BLACK — fațadă închisă, accente premium și look minimalist.",
      images: [
        "/brand/models/iconic-1story-black/01.jpg",
        "/brand/models/iconic-1story-black/02.jpg",
        "/brand/models/iconic-1story-black/03.jpg",
        "/brand/models/iconic-1story-black/04.jpg",
        "/brand/models/iconic-1story-black/05.jpg",
        "/brand/models/iconic-1story-black/06.jpg",
        "/brand/models/iconic-1story-black/07.jpg",
        "/brand/models/iconic-1story-black/08.jpg",
        "/brand/models/iconic-1story-black/09.jpg",
        "/brand/models/iconic-1story-black/10.jpg",
        "/brand/models/iconic-1story-black/11.jpg",
        "/brand/models/iconic-1story-black/12.jpg",
        "/brand/models/iconic-1story-black/13.jpg",
        "/brand/models/iconic-1story-black/14.jpg",
        "/brand/models/iconic-1story-black/15.jpg",
        "/brand/models/iconic-1story-black/16.jpg",
        "/brand/models/iconic-1story-black/17.jpg",
        
      ],
    },
    {
      slug: "iconic-1story-white",
      name: "CASA PARTER-iCONiC 1-story WHITE",
      summary: "Varianta WHITE — fațadă deschisă, contrast elegant și lumină maximă.",
      images: [
        "/brand/models/iconic-1story-white/01.jpg",
        "/brand/models/iconic-1story-white/02.jpg",
        "/brand/models/iconic-1story-white/03.jpg",
        "/brand/models/iconic-1story-white/04.jpg",
        "/brand/models/iconic-1story-white/05.jpg",
        "/brand/models/iconic-1story-white/06.jpg",
        "/brand/models/iconic-1story-white/07.jpg",
        "/brand/models/iconic-1story-white/08.jpg",
        "/brand/models/iconic-1story-white/09.jpg",
        "/brand/models/iconic-1story-white/10.jpg",
        "/brand/models/iconic-1story-white/11.jpg",
        "/brand/models/iconic-1story-white/12.jpg",
        "/brand/models/iconic-1story-white/13.jpg",
      ],
    },
    {
      slug: "iconic-1story-stone",
      name: "CASA PARTER-iCONiC 1-story STONE",
      summary: "Varianta STONE — fațadă din piatră, aspect solid și contrast modern.",
      images: [
        "/brand/models/iconic-1story-stone/01.jpg",
        "/brand/models/iconic-1story-stone/02.jpg",
        "/brand/models/iconic-1story-stone/03.jpg",
        "/brand/models/iconic-1story-stone/04.jpg",
        "/brand/models/iconic-1story-stone/05.jpg",
        "/brand/models/iconic-1story-stone/06.jpg",
        "/brand/models/iconic-1story-stone/07.jpg",
        "/brand/models/iconic-1story-stone/08.jpg",
        "/brand/models/iconic-1story-stone/09.jpg",
        "/brand/models/iconic-1story-stone/10.jpg",
        "/brand/models/iconic-1story-stone/11.jpg",
        "/brand/models/iconic-1story-stone/12.jpg",
        "/brand/models/iconic-1story-stone/13.jpg",
      ],
    },
    {
      slug: "iconic-1story-WoodSkin",
      name: "CASA PARTER-iCONiC 1-story WoodSkin",
      summary: "Varianta WoodSkin — fațadă ce imita lemnul, aspect cald și contrast modern.",
      images: [
        "/brand/models/iconic-1story-woodskin/01.jpg",
        "/brand/models/iconic-1story-woodskin/02.jpg",
        "/brand/models/iconic-1story-woodskin/03.jpg",
        "/brand/models/iconic-1story-woodskin/04.jpg",
        "/brand/models/iconic-1story-woodskin/05.jpg",
        "/brand/models/iconic-1story-woodskin/06.jpg",
        "/brand/models/iconic-1story-woodskin/07.jpg",
        "/brand/models/iconic-1story-woodskin/08.jpg",
        "/brand/models/iconic-1story-woodskin/09.jpg",
        "/brand/models/iconic-1story-woodskin/10.jpg",
        "/brand/models/iconic-1story-woodskin/11.jpg",
        "/brand/models/iconic-1story-woodskin/12.jpg",
        "/brand/models/iconic-1story-woodskin/13.jpg",
        "/brand/models/iconic-1story-woodskin/14.jpg",
      ],
    },

    {
      slug: "iconic-1story-black SCANDINAVIA",
      name: "CASA PARTER-iCONiC 1-story black SCANDINAVIA",
      summary: "Varianta BLACK — Casă modernă cu influență scandinavă, definită de volum clar, acoperiș și învelitoare/fațadă din tablă fălțuită neagră. Designul pune accent pe lumină naturală, vitrări ample, proporții curate și un aspect premium.",
      images: [
        "/brand/models/iconic-1story-black SCANDINAVIA/01.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/02.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/03.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/04.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/05.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/06.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/07.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/08.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/09.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/10.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/11.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/12.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/13.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/14.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/15.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/16.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/17.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/18.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/19.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/20.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/21.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/22.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/23.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/24.jpg",
        "/brand/models/iconic-1story-black SCANDINAVIA/25.jpg",
        
      ],
    },
{
  slug: "iconic-2story-black-monolith",
  name: "CASA cu ETAJ -iCONiC 2-story BLACK MONOLITH",
  summary: "Varianta BLACK MONOLITH — casă contemporană cu arhitectură monolitică, fațadă dark, detalii premium și estetică minimalistă, definită de volume curate, contraste rafinate și prezență puternică.",
  images: [
    "/brand/models/iconic-2story-black MONOLITH/01.jpg",
    "/brand/models/iconic-2story-black MONOLITH/02.jpg",
    "/brand/models/iconic-2story-black MONOLITH/03.jpg",
    "/brand/models/iconic-2story-black MONOLITH/04.jpg",
    "/brand/models/iconic-2story-black MONOLITH/05.jpg",
    "/brand/models/iconic-2story-black MONOLITH/06.jpg",
    "/brand/models/iconic-2story-black MONOLITH/07.jpg",
    "/brand/models/iconic-2story-black MONOLITH/08.jpg",
    "/brand/models/iconic-2story-black MONOLITH/09.jpg",
    "/brand/models/iconic-2story-black MONOLITH/10.jpg",
    "/brand/models/iconic-2story-black MONOLITH/11.jpg",
    "/brand/models/iconic-2story-black MONOLITH/12.jpg",
    "/brand/models/iconic-2story-black MONOLITH/13.jpg",
    "/brand/models/iconic-2story-black MONOLITH/14.jpg",
    "/brand/models/iconic-2story-black MONOLITH/15.jpg",
    "/brand/models/iconic-2story-black MONOLITH/16.jpg",
  ],
}
  ] as const,

  proces: {
    title: "Standardul nostru de proiectare",
    items: [
      {
        title: "Siguranță seismică tratată responsabil",
        text: "Proiectăm structura pentru o comportare seismică corectă, cu soluții coerente și controlate."
      },
      {
        title: "Soluție structurală aleasă rațional",
        text: "Alegem structura în funcție de teren, arhitectură, deschideri, utilizare și comportarea dorită în timp."
      },
      {
        title: "Eficiență energetică și principii NZEB",
        text: "Integrăm soluții compatibile cu cerințele actuale de performanță energetică și cu principiile NZEB."
      },
      {
        title: "Proiectare în interesul clientului",
        text: "Urmărim siguranța, durabilitatea și avantajul real al beneficiarului, nu economii false pe termen scurt."
      },
    ],
  },

contact: {
  title: "Hai să discutăm despre proiectul tău",
  phone: "+40 741 259 236",
  email: "contact@iconic-collection.ro",
  note: "Dacă ai deja terenul sau doar ideea de la care vrei să pornești, ne poți scrie. Îți răspundem clar și îți spunem ce pași urmează.",
  address: "Sector 3, Str. Agatha Bârsescu Nr. 15B, Etaj 01, Biroul 7, București",
  program: "Luni–Vineri 09:00–18:00",
  mapEmbedUrl: "https://www.google.com/maps?q=Strada%20Agatha%20Barsescu%2015B%20Bucuresti&z=16&output=embed",
},

  social: {
    facebook: "#",
    instagram: "#",
    linkedin: "#",
  },
} as const;
