export const site = {
  brandName: "iCONiC collection",
  siteUrl: "https://www.iconic-collection.ro",
  headline: "Case proiectate și executate corect, personalizate pentru terenul tău, conform reglementărilor urbanistice",
  subheadline:
    "Tu vii cu terenul și obiectivul, iar noi ne putem ocupa de ce ai nevoie: concept, studiu geotehnic, proiect complet (arhitectură, structură și instalații), documentații pentru autorizare, urmărire de șantier, dirigenție și execuție.",
  heroBadges: [
    "Proiectare completă pentru casă",
    "Documentații și pași pentru autorizare",
    "Execuție și coordonare până la capăt",
  ],
  cta: {
    primary: { label: "Contactează-ne", href: "/contact" },
    secondary: { label: "Vezi modele", href: "/modele" },
  },

  pachete: {
    title: "Pașii Proiectului",
    items: [
      "Discuția inițială și analiza terenului",
      "Ridicare topografică",
      "Studiu geotehnic",
      "Conceptul casei și organizarea soluției",
      "Documentația pentru autorizare",
      "Proiectul tehnic și detaliile de execuție",
      "Coordonare și clarificări pe parcurs",
      "Execuție",
    ],
    actions: [{ label: "Vezi pașii proiectului", href: "/pachete" }],
  },

  models: [
    {
      slug: "iconic-1story-black",
      name: "CASA PARTER-iCONiC 1-story BLACK",
      summary: "Varianta BLACK — fațadă închisă, accente premium și look minimalist.",
      images: [
        "/brand/models/iconic-1story-black/01.jpg",
        "/brand/models/iconic-1story-black/02.jpg",
        "/brand/models/iconic-1story-black/03.jpg",
        "/brand/models/iconic-1story-black/04.jpg",
        "/brand/models/iconic-1story-black/05.jpg",
        "/brand/models/iconic-1story-black/06.jpg",
        "/brand/models/iconic-1story-black/07.jpg",
        "/brand/models/iconic-1story-black/08.jpg",
        "/brand/models/iconic-1story-black/09.jpg",
        "/brand/models/iconic-1story-black/10.jpg",
        "/brand/models/iconic-1story-black/11.jpg",
        "/brand/models/iconic-1story-black/12.jpg",
        "/brand/models/iconic-1story-black/13.jpg",
        "/brand/models/iconic-1story-black/14.jpg",
        "/brand/models/iconic-1story-black/15.jpg",
        "/brand/models/iconic-1story-black/16.jpg",
        "/brand/models/iconic-1story-black/17.jpg",
        
      ],
    },
    {
      slug: "iconic-1story-white",
      name: "CASA PARTER-iCONiC 1-story WHITE",
      summary: "Varianta WHITE — fațadă deschisă, contrast elegant și lumină maximă.",
      images: [
        "/brand/models/iconic-1story-white/01.jpg",
        "/brand/models/iconic-1story-white/02.jpg",
        "/brand/models/iconic-1story-white/03.jpg",
        "/brand/models/iconic-1story-white/04.jpg",
        "/brand/models/iconic-1story-white/05.jpg",
        "/brand/models/iconic-1story-white/06.jpg",
        "/brand/models/iconic-1story-white/07.jpg",
        "/brand/models/iconic-1story-white/08.jpg",
        "/brand/models/iconic-1story-white/09.jpg",
        "/brand/models/iconic-1story-white/10.jpg",
        "/brand/models/iconic-1story-white/11.jpg",
        "/brand/models/iconic-1story-white/12.jpg",
        "/brand/models/iconic-1story-white/13.jpg",
      ],
    },
    {
      slug: "iconic-1story-stone",
      name: "CASA PARTER-iCONiC 1-story STONE",
      summary: "Varianta STONE — fațadă din piatră, aspect solid și contrast modern.",
      images: [
        "/brand/models/iconic-1story-stone/01.jpg",
        "/brand/models/iconic-1story-stone/02.jpg",
        "/brand/models/iconic-1story-stone/03.jpg",
        "/brand/models/iconic-1story-stone/04.jpg",
        "/brand/models/iconic-1story-stone/05.jpg",
        "/brand/models/iconic-1story-stone/06.jpg",
        "/brand/models/iconic-1story-stone/07.jpg",
        "/brand/models/iconic-1story-stone/08.jpg",
        "/brand/models/iconic-1story-stone/09.jpg",
        "/brand/models/iconic-1story-stone/10.jpg",
        "/brand/models/iconic-1story-stone/11.jpg",
        "/brand/models/iconic-1story-stone/12.jpg",
        "/brand/models/iconic-1story-stone/13.jpg",
      ],
    },
    {
      slug: "iconic-1story-WoodSkin",
      name: "CASA PARTER-iCONiC 1-story WoodSkin",
      summary: "Varianta WoodSkin — fațadă ce imita lemnul, aspect cald și contrast modern.",
      images: [
        "/brand/models/iconic-1story-woodskin/01.jpg",
        "/brand/models/iconic-1story-woodskin/02.jpg",
        "/brand/models/iconic-1story-woodskin/03.jpg",
        "/brand/models/iconic-1story-woodskin/04.jpg",
        "/brand/models/iconic-1story-woodskin/05.jpg",
        "/brand/models/iconic-1story-woodskin/06.jpg",
        "/brand/models/iconic-1story-woodskin/07.jpg",
        "/brand/models/iconic-1story-woodskin/08.jpg",
        "/brand/models/iconic-1story-woodskin/09.jpg",
        "/brand/models/iconic-1story-woodskin/10.jpg",
        "/brand/models/iconic-1story-woodskin/11.jpg",
        "/brand/models/iconic-1story-woodskin/12.jpg",
        "/brand/models/iconic-1story-woodskin/13.jpg",
        "/brand/models/iconic-1story-woodskin/14.jpg",
      ],
    },

{
slug: "iconic-1story-black-Scandinavia",
name: "Casă parter iCONiC 1-Story black Scandinavia",
summary: "Varianta BLACK — Casă modernă cu influență scandinavă, definită de volum clar, acoperiș și învelitoare/fațadă din tablă fălțuită neagră. Designul pune accent pe lumină naturală, vitrări ample, proporții curate și un aspect premium.",
images: [
  "/brand/models/iconic-1story-black Scandinavia/01.jpg",
  "/brand/models/iconic-1story-black Scandinavia/02.jpg",
  "/brand/models/iconic-1story-black Scandinavia/03.jpg",
  "/brand/models/iconic-1story-black Scandinavia/04.jpg",
  "/brand/models/iconic-1story-black Scandinavia/05.jpg",
  "/brand/models/iconic-1story-black Scandinavia/06.jpg",
  "/brand/models/iconic-1story-black Scandinavia/07.jpg",
  "/brand/models/iconic-1story-black Scandinavia/08.jpg",
  "/brand/models/iconic-1story-black Scandinavia/09.jpg",
  "/brand/models/iconic-1story-black Scandinavia/10.jpg",
  "/brand/models/iconic-1story-black Scandinavia/11.jpg",
  "/brand/models/iconic-1story-black Scandinavia/12.jpg",
  "/brand/models/iconic-1story-black Scandinavia/13.jpg",
  "/brand/models/iconic-1story-black Scandinavia/14.jpg",
  "/brand/models/iconic-1story-black Scandinavia/15.jpg",
  "/brand/models/iconic-1story-black Scandinavia/16.jpg",
  "/brand/models/iconic-1story-black Scandinavia/17.jpg",
  "/brand/models/iconic-1story-black Scandinavia/18.jpg",
  "/brand/models/iconic-1story-black Scandinavia/19.jpg",
  "/brand/models/iconic-1story-black Scandinavia/20.jpg",
  "/brand/models/iconic-1story-black Scandinavia/21.jpg",
  "/brand/models/iconic-1story-black Scandinavia/22.jpg",
 ],
},

{
slug: "iconic-1story-WoodSkin-Scandinavia",
name: "Casă parter iCONiC 1-Story WoodSkin Scandinavia",
summary: "Varianta WoodSkin — Casă modernă cu influență scandinavă, fatada deschisa definită de volum clar, acoperiș și învelitoare/fațadă din tablă fălțuită neagră. Designul pune accent pe lumină naturală, vitrări ample, proporții curate și un aspect premium.",
images: [
  "/brand/models/iconic-1story-WoodSkin Scandinavia/01.jpg",
  "/brand/models/iconic-1story-WoodSkin Scandinavia/02.jpg",
  "/brand/models/iconic-1story-WoodSkin Scandinavia/03.jpg",
  "/brand/models/iconic-1story-WoodSkin Scandinavia/04.jpg",
  "/brand/models/iconic-1story-WoodSkin Scandinavia/05.jpg",
  "/brand/models/iconic-1story-WoodSkin Scandinavia/06.jpg",
  "/brand/models/iconic-1story-WoodSkin Scandinavia/07.jpg",
  "/brand/models/iconic-1story-WoodSkin Scandinavia/08.jpg",
  "/brand/models/iconic-1story-WoodSkin Scandinavia/09.jpg",
  "/brand/models/iconic-1story-WoodSkin Scandinavia/10.jpg",
  "/brand/models/iconic-1story-WoodSkin Scandinavia/11.jpg",
 ],
},
{
  slug: "iconic-Metropolitan",
  name: "CASA iCONiC-Metropolitan",
  summary: "Varianta Metropolitan Contemporan — casă cu eleganță contemporană, fațadă luminoasă cu o prezență rafinată modernistă.",
  images: [
    "/brand/models/iconic-Metropolitan/01.jpg",
    "/brand/models/iconic-Metropolitan/02.jpg",
    "/brand/models/iconic-Metropolitan/03.jpg",
    "/brand/models/iconic-Metropolitan/04.jpg",
    "/brand/models/iconic-Metropolitan/05.jpg",
    "/brand/models/iconic-Metropolitan/06.jpg",
    "/brand/models/iconic-Metropolitan/07.jpg",
    "/brand/models/iconic-Metropolitan/08.jpg",
    "/brand/models/iconic-Metropolitan/09.jpg",
    "/brand/models/iconic-Metropolitan/10.jpg",
    "/brand/models/iconic-Metropolitan/11.jpg",
    "/brand/models/iconic-Metropolitan/12.jpg",
    "/brand/models/iconic-Metropolitan/13.jpg",
    "/brand/models/iconic-Metropolitan/14.jpg",
  ],
},

  
{
  slug: "iconic-Metropolitan-Prime",
  name: "CASA iCONiC-Metropolitan Prime",
  summary: "Varianta Metropolitan Prime — casă cu eleganță contemporană, fațadă cu linii curate, cu o prezență rafinată și modernistă.",
  images: [
    "/brand/models/iconic-Metropolitan Prime/01.jpg",
    "/brand/models/iconic-Metropolitan Prime/02.jpg",
    "/brand/models/iconic-Metropolitan Prime/03.jpg",
    "/brand/models/iconic-Metropolitan Prime/04.jpg",
    "/brand/models/iconic-Metropolitan Prime/05.jpg",
    "/brand/models/iconic-Metropolitan Prime/06.jpg",
    "/brand/models/iconic-Metropolitan Prime/07.jpg",
    "/brand/models/iconic-Metropolitan Prime/08.jpg",
    "/brand/models/iconic-Metropolitan Prime/09.jpg",
    "/brand/models/iconic-Metropolitan Prime/10.jpg",
    "/brand/models/iconic-Metropolitan Prime/11.jpg",
    "/brand/models/iconic-Metropolitan Prime/12.jpg", 
    "/brand/models/iconic-Metropolitan Prime/13.jpg", 
    "/brand/models/iconic-Metropolitan Prime/14.jpg", 
    "/brand/models/iconic-Metropolitan Prime/15.jpg", 
    "/brand/models/iconic-Metropolitan Prime/16.jpg",
    "/brand/models/iconic-Metropolitan Prime/17.jpg",
    "/brand/models/iconic-Metropolitan Prime/18.jpg",
  ],
},

{
  slug: "iconic-North-Line",
  name: "CASA iCONiC-North Line",
  summary: "Casă premium cu volumetrie clară, materiale naturale și o imagine arhitecturală calmă, coerentă și actuală.",
  images: [
    "/brand/models/iconic-North Line/01.jpg",
    "/brand/models/iconic-North Line/02.jpg",
    "/brand/models/iconic-North Line/03.jpg",
    "/brand/models/iconic-North Line/04.jpg",
    "/brand/models/iconic-North Line/05.jpg",
    "/brand/models/iconic-North Line/06.jpg",
    "/brand/models/iconic-North Line/07.jpg",
    "/brand/models/iconic-North Line/08.jpg",
    "/brand/models/iconic-North Line/09.jpg",
  ],
},
{
  slug: "iconic-CUBE-FRAME",
  name: "CASA iCONiC-CUBE FRAME",
  summary: "Varianta CUBE FRAME — Casă premium, cu volumetrie curată și expresie contemporană.",
  images: [
    "/brand/models/iconic-CUBE-FRAME/01.jpg",
    "/brand/models/iconic-CUBE-FRAME/02.jpg",
    "/brand/models/iconic-CUBE-FRAME/03.jpg",
    "/brand/models/iconic-CUBE-FRAME/04.jpg",
  ],
},

{
  slug: "iconic-Boxline-House",
  name: "CASA iCONiC-Boxline House",
  summary: "Varianta Boxline House — casă tip boxline contemporană, fațadă luminoasă cu o prezență rafinată modernistă.",
  images: [
    "/brand/models/iconic-Boxline House/01.jpg",
    "/brand/models/iconic-Boxline House/02.jpg",
    "/brand/models/iconic-Boxline House/03.jpg",
    "/brand/models/iconic-Boxline House/04.jpg",
    "/brand/models/iconic-Boxline House/05.jpg",
    "/brand/models/iconic-Boxline House/06.jpg",
    "/brand/models/iconic-Boxline House/07.jpg",
    "/brand/models/iconic-Boxline House/08.jpg",
    "/brand/models/iconic-Boxline House/09.jpg",
    "/brand/models/iconic-Boxline House/10.jpg",
  ],
},

{
  slug: "iconic-DISTRICT",
  name: "CASA iCONiC-DISTRICT",
  summary: "Varianta DISTRICT — Casă premium, cu volumetrie curată și expresie contemporană iberica.",
  images: [
    "/brand/models/iconic-DISTRICT/01.jpg",
    "/brand/models/iconic-DISTRICT/02.jpg",
    "/brand/models/iconic-DISTRICT/03.jpg",
    "/brand/models/iconic-DISTRICT/04.jpg",
  ],
},
{
  slug: "iconic-2story-black-monolith",
  name: "CASA cu ETAJ -iCONiC 2-story BLACK MONOLITH",
  summary: "Varianta BLACK MONOLITH — casă contemporană cu arhitectură monolitică, fațadă dark, detalii premium și estetică minimalistă, definită de volume curate, contraste rafinate și prezență puternică.",
  images: [
    "/brand/models/iconic-2story-black MONOLITH/01.jpg",
    "/brand/models/iconic-2story-black MONOLITH/02.jpg",
    "/brand/models/iconic-2story-black MONOLITH/03.jpg",
    "/brand/models/iconic-2story-black MONOLITH/04.jpg",
    "/brand/models/iconic-2story-black MONOLITH/05.jpg",
    "/brand/models/iconic-2story-black MONOLITH/06.jpg",
    "/brand/models/iconic-2story-black MONOLITH/07.jpg",
    "/brand/models/iconic-2story-black MONOLITH/08.jpg",
    "/brand/models/iconic-2story-black MONOLITH/09.jpg",
    "/brand/models/iconic-2story-black MONOLITH/10.jpg",
    "/brand/models/iconic-2story-black MONOLITH/11.jpg",
    "/brand/models/iconic-2story-black MONOLITH/12.jpg",
    "/brand/models/iconic-2story-black MONOLITH/13.jpg",
    "/brand/models/iconic-2story-black MONOLITH/14.jpg",
    "/brand/models/iconic-2story-black MONOLITH/15.jpg",
    "/brand/models/iconic-2story-black MONOLITH/16.jpg",
  ],
},

{
  slug: "iconic-MONOLITH-BRICK",
  name: "CASA cu ETAJ -iconic-MONOLITH BRICK",
  summary: "Varianta MONOLITH BRICK — casă contemporană cu volumetrie monolitică, fațade minerale deschise și ancadramente negre adâncite, gândită pentru o imagine sobră, elegantă și premium",
  images: [
    "/brand/models/iconic-MONOLITH BRICK/01.jpg",
    "/brand/models/iconic-MONOLITH BRICK/02.jpg",
    "/brand/models/iconic-MONOLITH BRICK/03.jpg",
    "/brand/models/iconic-MONOLITH BRICK/04.jpg",
    "/brand/models/iconic-MONOLITH BRICK/05.jpg",
    "/brand/models/iconic-MONOLITH BRICK/06.jpg",
    "/brand/models/iconic-MONOLITH BRICK/07.jpg",
    "/brand/models/iconic-MONOLITH BRICK/08.jpg",
    "/brand/models/iconic-MONOLITH BRICK/09.jpg",
    "/brand/models/iconic-MONOLITH BRICK/10.jpg",
    "/brand/models/iconic-MONOLITH BRICK/11.jpg",
    "/brand/models/iconic-MONOLITH BRICK/12.jpg",
    "/brand/models/iconic-MONOLITH BRICK/13.jpg",
    "/brand/models/iconic-MONOLITH BRICK/14.jpg",
  ],
},
{
  slug: "iconic-MONOLITH-URBAN-BRICK",
  name: "CASA cu ETAJ -iconic-MONOLITH URBAN-BRICK",
  summary: "Varianta MONOLITH URBAN-BRICK — casă contemporană cu volumetrie monolitică, fațade minerale deschise și ancadramente negre adâncite, gândită pentru o imagine sobră, elegantă și premium",
  images: [
    "/brand/models/iconic-MONOLITH URBAN-BRICK/01.jpg",
    "/brand/models/iconic-MONOLITH URBAN-BRICK/02.jpg",
    "/brand/models/iconic-MONOLITH URBAN-BRICK/03.jpg",
    "/brand/models/iconic-MONOLITH URBAN-BRICK/04.jpg",
    "/brand/models/iconic-MONOLITH URBAN-BRICK/05.jpg",
    "/brand/models/iconic-MONOLITH URBAN-BRICK/06.jpg",
    "/brand/models/iconic-MONOLITH URBAN-BRICK/07.jpg",
    "/brand/models/iconic-MONOLITH URBAN-BRICK/08.jpg",
    "/brand/models/iconic-MONOLITH URBAN-BRICK/09.jpg",
    "/brand/models/iconic-MONOLITH URBAN-BRICK/10.jpg",
    "/brand/models/iconic-MONOLITH URBAN-BRICK/11.jpg",
    "/brand/models/iconic-MONOLITH URBAN-BRICK/12.jpg",
    "/brand/models/iconic-MONOLITH URBAN-BRICK/13.jpg",
    "/brand/models/iconic-MONOLITH URBAN-BRICK/14.jpg",
  ],
},    
{
  slug: "iconic-2story-black-monolith-125",
  name: "CASA cu ETAJ -iCONiC MONOLITH 125",
  summary: "Varianta BLACK MONOLITH 125— casă creată pentru cei care caută claritate, ordine și un dialog vizual constant cu exteriorul, totul într-un pachet arhitectural de o eleganță atemporală.",
  images: [
    "/brand/models/iconic-2story-black MONOLITH 125/01.jpg",
    "/brand/models/iconic-2story-black MONOLITH 125/02.jpg",
    "/brand/models/iconic-2story-black MONOLITH 125/03.jpg",
    "/brand/models/iconic-2story-black MONOLITH 125/04.jpg",
  ],
},

    
{
  slug: "iconic-Bucharest",
  name: "CASA iCONiC-Bucharest",
  summary: "Varianta NEO INTERBELIC — casă cu eleganță interbelică reinterpretată, proporții echilibrate, fațadă luminoasă și detalii clasice simplificate, cu o prezență rafinată și atemporală.",
  images: [
    "/brand/models/iconic-Bucharest/01.jpg",
    "/brand/models/iconic-Bucharest/02.jpg",
    "/brand/models/iconic-Bucharest/03.jpg",
    "/brand/models/iconic-Bucharest/04.jpg",
    "/brand/models/iconic-Bucharest/05.jpg",
    "/brand/models/iconic-Bucharest/06.jpg",
    "/brand/models/iconic-Bucharest/07.jpg",
    "/brand/models/iconic-Bucharest/08.jpg",
    "/brand/models/iconic-Bucharest/09.jpg",
    "/brand/models/iconic-Bucharest/10.jpg",
    "/brand/models/iconic-Bucharest/11.jpg",    
  ],
},

{
  slug: "iconic-Bucharest-PREMIUM",
  name: "CASA iCONiC-Bucharest PREMIUM",
  summary: "Varianta PREMIUM — casă cu eleganță si proporții echilibrate, fațadă luminoasă și detalii clasice simplificate, cu o prezență rafinată și atemporală.",
  images: [
    "/brand/models/iconic-Bucharest PREMIUM/01.jpg",
    "/brand/models/iconic-Bucharest PREMIUM/02.jpg",
    "/brand/models/iconic-Bucharest PREMIUM/03.jpg",
    "/brand/models/iconic-Bucharest PREMIUM/04.jpg",
    "/brand/models/iconic-Bucharest PREMIUM/05.jpg",
    "/brand/models/iconic-Bucharest PREMIUM/06.jpg",
    "/brand/models/iconic-Bucharest PREMIUM/07.jpg",
  ],
}    
  ] as const,

  proces: {
    title: "Standardul nostru de proiectare",
    items: [
      {
        title: "Siguranță seismică tratată responsabil",
        text: "Proiectăm structura pentru o comportare seismică corectă, cu soluții coerente și controlate."
      },
      {
        title: "Soluție structurală aleasă rațional",
        text: "Alegem structura în funcție de teren, arhitectură, deschideri, utilizare și comportarea dorită în timp."
      },
      {
        title: "Eficiență energetică și principii NZEB",
        text: "Integrăm soluții compatibile cu cerințele actuale de performanță energetică și cu principiile NZEB."
      },
      {
        title: "Proiectare în interesul clientului",
        text: "Urmărim siguranța, durabilitatea și avantajul real al beneficiarului, nu economii false pe termen scurt."
      },
    ],
  },

contact: {
  title: "Hai să discutăm despre proiectul tău",
  phone: "0741 259 236",
  phoneLink: "+40741259236",
  email: "contact@iconic-collection.ro",
  note: "Dacă ai deja terenul sau doar ideea de la care vrei să pornești, ne poți scrie. Îți răspundem clar și îți spunem ce pași urmează.",
  address: "Sector 3, Str. Agatha Bârsescu Nr. 15B, Etaj 01, Biroul 7, București",
  program: "Luni–Vineri 09:00–18:00",
  mapEmbedUrl: "https://www.google.com/maps?q=Strada%20Agatha%20Barsescu%2015B%20Bucuresti&z=16&output=embed",
},

  social: {
    facebook: "#",
    instagram: "#",
    linkedin: "#",
  },
} as const;
